import { Inter } from "next/font/google";
import "./globals.css";
import "/public/style.css";
import Script from "next/script";
import { GlobalProvider } from "@/context/GlobalProvider";
import Header from "@/components/header/Header";
import "@/styles/flame.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <GlobalProvider>{children}</GlobalProvider>
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
          crossOrigin="anonymous"
        />
      </body>
    </html>
  );
}
